name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Staging
      run: echo "deployed successfully"
