name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying to Production"
      - name: Report deployment status
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: process.env.DEPLOYMENT_ID,
              state: 'success'
            });
            console.log(response);
